version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "daily"
      time: "15:30"
      timezone: "Australia/Melbourne"
    commit-message:
      prefix: fix
      include: scope
    labels:
      - github-actions

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "17:30"
      timezone: "Australia/Melbourne"
    commit-message:
      prefix: fix
      include: scope
    labels:
      - docker

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:30"
      timezone: "Australia/Melbourne"
    commit-message:
      prefix: fix
      include: scope
    labels:
      - npm
