version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "daily"
      time: "15:30"
      timezone: "Australia/Melbourne"
    labels:
      - github-actions

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "20:30"
      timezone: "Australia/Melbourne"
    labels:
      - docker
