# todo: Run make ci after everything else
# todo: Run Conventonal commit first
# todo: work out a way of keeping the versions in this file updated
# pre-commit does not have native dependency handling
# the commit-msg phase of git runs after the pre-commit phase

default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push
default_stages: [pre-commit]
fail_fast: true
repos:
  # Conventional commits enforcement
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  # Official Pre-Commit Checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # File hygiene
      - id: trailing-whitespace # Removes trailing whitespace
      - id: end-of-file-fixer # Ensures files end with a newline
      # File format validation
      - id: check-yaml # Validates YAML syntax
        args: [--allow-multiple-documents]
      - id: check-json # Validates JSON syntax
      - id: check-toml # Validates TOML syntax
      - id: check-xml # Validates XML syntax
      # Git specific
      - id: check-merge-conflict # Checks for files containing merge conflict strings
      # General checks
      - id: check-added-large-files # Prevents giant files from being committed
        args: ["--maxkb=500"]
  # Security scanning
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.22.1
    hooks:
      - id: gitleaks # Scan for hardcoded secrets
  # Local CI Pipeline
  - repo: local
    hooks:
      - id: make-ci
        exclude: "^(README.md)"
        name: make ci
        entry: make ci
        language: system
        pass_filenames: false
