# .github/workflows/ci.yml
name: ci

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  ci-build-test-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: build
      run: make build

    - name: setup bats
      id: setup-bats
      uses: bats-core/bats-action@3.0.1
      with:
        support-install: false
        assert-install: false
        detik-install: false
        file-install: false

    - name: smoke tests
      shell: bash
      env:
        BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        TERM: xterm
        BATS_FORMAT: tap
      run: make smoke


    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Release
      id: semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release

    - name: Login to Docker Hub
      if: steps.semantic-release.outputs.new_release_published == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: steps.semantic-release.outputs.new_release_published == 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.semantic-release.outputs.new_release_version }}
