# .github/workflows/ci.yml
name: ci

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'

permissions:
  contents: write

jobs:
  ci-build-test-release:
    runs-on: ubuntu-latest
    environment: ci

    steps:
    - name: Check out code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Add node_modules/.bin to PATH
      run: echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH

    - name: npm clean install
      run: npm ci

    - name: lint
      run: make lint

    - name: build
      run: make build

    - name: smoke tests
      shell: bash
      env:
        TERM: xterm
        BATS_FORMAT: tap
      run: make smoke

    - name: Semantic Release
      id: semantic-release
      uses: cycjimmy/semantic-release-action@v4
      with:
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
          semantic-release-replace-plugin
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Login to Docker Hub
      if: steps.semantic-release.outputs.new_release_published == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: steps.semantic-release.outputs.new_release_published == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.semantic-release.outputs.new_release_version }}

    - name: Discord Alert
      uses: sarisia/actions-status-discord@v1
      if: failure()
      with:
        username: GitHub Workflow Alert
        content: "${{ github.event.repository.name }} ${{ github.workflow }} workflow has failed, tell @everyone"
        url: "https://github.com/jamiemoore/tools/actions/workflows/ci.yml"
        webhook: ${{ secrets.DISCORD_WEBHOOK }}

    - name: healthcheck ping
      if: success()
      run: curl -m 10 --retry 5 ${{ secrets.PING_URL }}
